name: Nightly Build (dev)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'

    - name: Restore
      run: dotnet restore KernelExtensions.csproj

    - name: Build
      run: dotnet build KernelExtensions.csproj --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: KernelExtensions-Nightly
        path: bin/Release/net472/KernelExtensions.dll
